### ISSUE TITLE
coq fails to build

### ISSUE THREAD

**Issue by shubhamkumar13** [ocaml-bench/sandmark#248]
The build error occurs while running sandmark on navajo with 4.12.0+domains+effects variant.  But this doesn't seem to be limited to navajo because I got a similar error on my personal laptop

The following error log is from navajo.
```
[ERROR] The compilation of coq failed at "/local/scratch/shubham/sandmark/_opam/opam-init/hooks/sandbox.sh build dune build -p coq -j 127".

#=== ERROR while compiling coq.dev ============================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.12.0+domains+effects | file:///local/scratch/shubham/sandmark/dependencies
# path                 /local/scratch/shubham/sandmark/_opam/4.12.0+domains+effects/.opam-switch/build/coq.dev
# command              /local/scratch/shubham/sandmark/_opam/opam-init/hooks/sandbox.sh build dune build -p coq -j 127
# exit-code            137
# env-file             /local/scratch/shubham/sandmark/_opam/log/coq-2821127-2ffe40.env
# output-file          /local/scratch/shubham/sandmark/_opam/log/coq-2821127-2ffe40.out
### output ###
# 265 | let declare_coercion coef ?(local = false) ~isid ~src:cls ~target:clt ~params:ps =
# [...]
# Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
#     ocamlopt stm/.stm.objs/native/stm.{cmx,o}
# File "stm/stm.ml", line 1759, characters 24-27:
# 1759 |   let build_proof ~doc ?loc ~drop_pt ~exn_info ~block_start ~block_stop ~name:pname =
#                                ^^^
# Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
#     ocamlopt plugins/ssr/.ssreflect_plugin.objs/native/ssreflect_plugin__Ssrview.{cmx,o}
# File "plugins/ssr/ssrview.ml", line 396, characters 30-47:
# 396 | let tclIPAT_VIEWS ~views:vs ?(clear_if_id=false) ~conclusion =
#                                     ^^^^^^^^^^^^^^^^^
# Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
```

Steps to recreate the error:

1. Clone the sandmark repo 
```
git clone https://github.com/ocaml-bench/sandmark.git
```
2. Download the gist that has the coq benchmarks only (`run_config.json` present locally can also be used, it might take a lot of time and the other benchmarks are not important for this issue)
```
wget https://gist.githubusercontent.com/shubhamkumar13/ba9dc421a745d0d5f57d10409bf6e5a4/raw/c39ccf43cec129907f0f5adcc2422b4ef3fe6eaa/run_config.json coq_run_config.json -O coq_run_config.json
```
3. Run the following commands to start running the benchmark (if using `run_config.json` instead of the custom .json file interchange the `coq_run_config_filtered.json` with `run_config.json`)
```
TAG='"macro_bench"' make coq_run_config_filtered.json \

RUN_CONFIG_JSON=coq_run_config_filtered.json make ocaml-versions/4.12.0+domains+effects.bench
```

**Comment by Sudha247** [comment]
After looking at this for a bit, here are the findings:

* Coq version in sandmark seems a bit old. It doesn't support OCaml 4.12. The [patch to get Multicore working](https://github.com/ejgallego/coq/commit/f4c39b18d3a8a209a59d60736885f4480ea93238) may need an update. The systhreads changes are already fixed in the current Multicore branch, I believe.

* I attempted to build Coq `v8.13`. It builds with OCaml `4.12`. On OCaml `4.12.0+domains`, a few things might need patching up:
    - GC colours: Some places refer `Caml_black` and `Caml_white`, we can change this to `NOT_MARKABLE` and include relevant headers.
    - GC hooks: GC hook references need to be updated to the right name based on the branch.
    - `memory.h` macros: Some macros like `Alloc_small` have different number of arguments.
    - There could be other macros I have missed here that require updation.

**Comment by ejgallego** [comment]
Hi folks, thanks for bringing this into my attention. I will update the patch ASAP.

**Comment by ejgallego** [comment]
I have tried to update the patch at https://github.com/ejgallego/coq/tree/ocaml+multicore but indeed I'm getting a segfault in the GC:

```
0x00005555562735f3 in caml_darken (v=93825005886400, ignored=<optimized out>, state=<optimized out>) at major_gc.c:740
740	major_gc.c: No existe el archivo o el directorio.
(gdb) bt
#0  0x00005555562735f3 in caml_darken (v=93825005886400, ignored=<optimized out>, state=<optimized out>) at major_gc.c:740
#1  0x000055555628b393 in scan_native_globals (fdata=0x0, f=0x555556273640 <caml_darken>) at globroots.c:214
#2  caml_scan_global_roots (f=f@entry=0x555556273640 <caml_darken>, fdata=fdata@entry=0x0) at globroots.c:238
#3  0x0000555556273f78 in cycle_all_domains_callback (domain=0x555556a49710 <all_domains+16>, unused=unused@entry=0x0, participating_count=participating_count@entry=1, 
    participating=participating@entry=0x555556a492e0 <stw_request+4160>) at major_gc.c:1055
#4  0x0000555556294489 in caml_try_run_on_all_domains_with_spin_work (enter_spin_data=<optimized out>, enter_spin_callback=<optimized out>, 
    leader_setup=<optimized out>, data=<optimized out>, handler=<optimized out>) at domain.c:898
#5  caml_try_run_on_all_domains_with_spin_work (handler=<optimized out>, data=<optimized out>, leader_setup=<optimized out>, enter_spin_callback=<optimized out>, 
    enter_spin_data=<optimized out>) at domain.c:807
#6  0x0000555556274c36 in major_collection_slice (howmuch=<optimized out>, participant_count=participant_count@entry=0, 
    barrier_participants=barrier_participants@entry=0x0, mode=mode@entry=Slice_interruptible) at major_gc.c:1332
#7  0x0000555556274dc8 in caml_major_collection_slice (howmuch=howmuch@entry=-1) at major_gc.c:1351
#8  0x0000555556292ad5 in caml_poll_gc_work () at domain.c:962
#9  0x00005555562722d5 in caml_garbage_collection () at signals_nat.c:110
#10 0x000055555629617f in caml_call_gc ()

```

It could well be due to the hacks I'm doing to avoid the calling of Coq's VM machine written in C; but I am not sure.

**Comment by ejgallego** [comment]
Umm, actually I'm getting a segfault too when using the old branch https://github.com/ejgallego/coq/commit/f4c39b18d3a8a209a59d60736885f4480ea93238

**Comment by gadmm** [comment]
@ejgallego Don't you need the patch to double-make-sure that native compute is never used because of naked pointers ? (see e.g. https://github.com/gadmm/coq/commit/1ba07b808ba which was inspired from one of yours).

(Note : in stock+nnp, I still have a weird crash in one particular mathcomp lib despite this patch... something to investigate)

**Comment by shubhamkumar13** [comment]
@shakthimaan can this issue can be closed as the latest coq is now merged into sandmark?

**Comment by shakthimaan** [comment]
Yes. Closing the issue since coq 2019-09 has been updated to build with Sandmark.
